server:
  port: 10600
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:mall-nacos}:${NACOS_PORT:8868}
  profiles:
    active: @profiles.active@